<?php

namespace app\controllers;

use yii\web\Controller;


class StudyController extends Controller
{
//    public $defaultAction = 'home';
//
//    public function actionHome()
//    {
//        return '代替了默认的 action';
//    }

    public function actionIndex()
    {
        return $this->render('/site/study'); // /html/views/site/study.php
    }

    // 参数仅限用于 get 请求，一般情况下最好给默认值，否则将会报错（Missing required parameters: id）
    // 如果需要接收数组，需要显式指定 array（即使传递的不是数组，也会被转换成为数组）
    public function actionParams($id = 'default id', array $foods)
    {
        return var_dump($foods);
    }

    // 控制器生命周期
    // 1.
//    public function init()
//    {
//        echo 'init fn call';
//        parent::init();
//    }

    // 2.
//    public function beforeAction($action)
//    {
//        echo 'beforeAction fn call';
////        return false;
//        return parent::beforeAction($action); // TODO: Change the autogenerated stub
//    }

    // 3.
//    public function afterAction($action, $result)
//    {
//        echo 'afterAction fn call';
////        return false;
//        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
//    }

}

