<?php

namespace app\components;

use yii\base\ActionFilter;


class TestFilter extends ActionFilter
{
    public function beforeAction($action)
    {
        // return false; 后续的 filter 和 action 都不会再执行
        echo 'beforeAction' . '<br />';
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function afterAction($action, $result)
    {

//        var_dump($result);
        echo 'afterAction' . '<br />';
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }
}