<?php

namespace app\modules\test;


class Module extends \yii\base\Module
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        // init code ...
        $this->params['foo'] = 'bar';
    }
}